# Generated by Django 4.1.7 on 2023-04-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0003_moreartists_delete_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageName', models.CharField(max_length=50, verbose_name='Image Name')),
                ('Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicApp.image', verbose_name='Image')),
            ],
        ),
    ]
