# Generated by Django 4.2 on 2023-04-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
