# Generated by Django 4.2 on 2023-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0005_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoThumbnail', models.ImageField(help_text='.jpg,.png ,.jpeg, .gif, .svg supported', upload_to='thumbnail/', verbose_name='Video Thumbnail')),
                ('video', models.FileField(help_text='.mp4 spported only', upload_to='videos/', verbose_name='Video')),
                ('videoName', models.CharField(max_length=50, verbose_name='Video Name')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
