# Generated by Django 4.2 on 2023-04-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0006_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videoThumbnail',
        ),
    ]
