# Generated by Django 4.1.7 on 2023-04-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0008_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
