# Generated by Django 4.1.7 on 2023-04-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0009_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songThumbnails', models.ImageField(help_text='.jpg,.png ,.jpeg, .gif, .svg supported', upload_to='thumbnail/', verbose_name='Song Thumbnails')),
                ('songs', models.FileField(help_text='.mp3 spported only', upload_to='songs/', verbose_name='Songs')),
                ('songNames', models.CharField(max_length=50, verbose_name='Song Names')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Songs created date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Latest songs update')),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicApp.album', verbose_name='Song Albums')),
            ],
        ),
    ]
