# Generated by Django 4.1.7 on 2023-04-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0010_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoreArtists',
        ),
    ]
