# Generated by Django 4.1.7 on 2023-04-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0012_moreartists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='albums',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
